import type { GameDefinition } from '@/shared/types/game';

export const GAME_DEFINITIONS = [
  {
    id: 'finger-sumo',
    title: '핑거 스모',
    icon: '🥊',
    mode: '대전',
    durationSeconds: 30,
    accent: '#FF6B5F',
    description: '밀고 버텨서 원 밖으로!',
    rule: '캐릭터를 드래그해 상대를 경기장 밖으로 밀어내세요.',
  },
  {
    id: 'reaction-stop',
    title: '정지! 먼저 눌러',
    icon: '🚦',
    mode: '대전',
    durationSeconds: 10,
    accent: '#32C878',
    description: '초록불에 먼저 손 떼기',
    rule: '버튼을 누르고 기다리다가 초록불이 되면 먼저 손을 떼세요.',
  },
  {
    id: 'air-hockey',
    title: '미니 에어하키',
    icon: '🏒',
    mode: '대전',
    durationSeconds: 45,
    accent: '#4D8BFF',
    description: '한 화면에서 5골 승부',
    rule: '자기 진영의 패들을 움직여 퍽을 상대 골대에 넣으세요.',
  },
  {
    id: 'dual-rocket',
    title: '둘이서 로켓',
    icon: '🚀',
    mode: '협동',
    durationSeconds: 30,
    accent: '#8C6BFF',
    description: '엔진 하나씩 맡아 비행',
    rule: '각자 엔진 하나를 눌러 로켓의 상승과 방향을 함께 조종하세요.',
  },
  {
    id: 'couple-sync',
    title: '우리 얼마나 통할까',
    icon: '💞',
    mode: '커플',
    durationSeconds: 40,
    accent: '#FF65A5',
    description: '7문제로 보는 텔레파시',
    rule: '같은 질문에 답을 숨겨 고르고 두 사람의 선택을 확인하세요.',
  },
  {
    id: 'bomb-manual',
    title: '폭탄 설명서',
    icon: '💣',
    mode: '협동',
    durationSeconds: 45,
    accent: '#3B3B45',
    description: '설명하고 눌러서 해체',
    rule: 'P2는 규칙을 설명하고 P1은 45초 안에 세 단계를 입력하세요.',
  },
  {
    id: 'chicken-button',
    title: '치킨 버튼',
    icon: '🔥',
    mode: '대전',
    durationSeconds: 12,
    accent: '#FF9838',
    description: '폭발 직전까지 버티기',
    rule: '버튼을 오래 누르되 폭발하기 전에 손을 떼 점수를 지키세요.',
  },
  {
    id: 'color-trap',
    title: '색깔 함정',
    icon: '🎨',
    mode: '대전',
    durationSeconds: 40,
    accent: '#00A7A7',
    description: '글자 말고 진짜 색 찾기',
    rule: '글자의 뜻이 아니라 실제 글자색과 같은 버튼을 고르세요.',
  },
  {
    id: 'secret-prediction',
    title: '비밀 예측',
    icon: '🔮',
    mode: '커플',
    durationSeconds: 45,
    accent: '#7559C7',
    description: '상대의 선택을 읽어라',
    rule: '상대가 고를 답을 먼저 예측한 뒤 실제 답을 선택하세요.',
  },
  {
    id: 'tilt-maze',
    title: '기울기 미로',
    icon: '🌀',
    mode: '협동',
    durationSeconds: 45,
    accent: '#29A36A',
    description: '둘이 잡고 공 굴리기',
    rule: '휴대폰 양끝을 함께 잡고 기울여 체크포인트 세 개를 통과하세요.',
  },
] as const satisfies readonly GameDefinition[];

export function getGameDefinition(gameId: string): GameDefinition | undefined {
  const definition = GAME_DEFINITIONS.find(({ id }) => id === gameId);
  return definition;
}
